In [128]:
# from sklearn import svm,metrics
# from sklearn.neighbors import KNeighborsClassifier # 분류
# from sklearn.neighbors import KNeighborsRegressor # 회귀-예측
from sklearn.linear_model import LinearRegression # 선형회귀
from sklearn.preprocessing import PolynomialFeatures # 다항특성을 만들어주는 라이브러리
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False # 마이너스 표시 해결
# 한글설정
matplotlib.rcParams['font.family'] = 'Malgun Gothic' # Windows 사용자
# matplotlib.rcParams['font.family'] = 'Apple Gothic' # Mac 사용자
matplotlib.rcParams['font.size'] = 10 # 글자크기

In [129]:
df = pd.read_csv('https://bit.ly/fish_csv')
df.head(3)

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961

In [130]:
df.describe()

Weight      Length    Diagonal      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   28.415723   31.227044    8.970994    4.417486
std     357.978317   10.716328   11.610246    4.286208    1.685804
min       0.000000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   63.400000   68.000000   18.957000    8.142000

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Species   159 non-null    object 
 1   Weight    159 non-null    float64
 2   Length    159 non-null    float64
 3   Diagonal  159 non-null    float64
 4   Height    159 non-null    float64
 5   Width     159 non-null    float64
dtypes: float64(5), object(1)
memory usage: 7.6+ KB


In [132]:
# 데이터 확인: nan,0,타입, 최소값, 최대값 ,값이 분포, 각 특성별 데이터 최대값
# 1. 데이터 전처리 - data,target 분리
fish_input = df.iloc[:,1:].to_numpy()
fish_target = df['Species'].to_numpy()

In [133]:
# train,test 세트 분리
from sklearn.model_selection import train_test_split
train_input,test_input,train_target,test_target = train_test_split(
    fish_input,fish_target
)

In [134]:
# 표준화 작업
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [135]:
# 2. 데이터 실습
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(train_scaled,train_target)

LogisticRegression()

In [136]:
# 3. 데이터 예측
predict = lr.predict(test_scaled[:5])
print(predict)

['Perch' 'Smelt' 'Bream' 'Perch' 'Bream']


In [137]:
# 4. 데이터 정답률 - train,test
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

0.8235294117647058
0.775


#### 결과값 도출 형태 분석

In [142]:
predict = lr.predict(test_scaled[:5])
print(predict)

# 기울기,y절편의 값을 적용시켜서 z 점수 출력
# softMax함수를 적용해서 가장 높은 확률을 채택해서 결정함.

['Perch' 'Smelt' 'Bream' 'Perch' 'Bream']


In [143]:
lr.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [147]:
# 데이터 실습
from sklearn.linear_model import LogisticRegression
# max_iter: 반복횟수=100 기본설정
# C: 규제 => 올라가면 규제가 약해지고, 낮아지면 규제가 강해짐, - 선형회귀 규제 - alpha값으로 지정
lr = LogisticRegression(C=20,max_iter=1000)
lr.fit(train_scaled,train_target)

LogisticRegression(C=20, max_iter=1000)

In [148]:
# 데이터 정답률 - train,test
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

0.9411764705882353
0.875


In [149]:
lr.predict(test_scaled[:5])

array(['Perch', 'Smelt', 'Bream', 'Perch', 'Bream'], dtype=object)

In [150]:
proba = lr.predict_proba(test_scaled[:5])
print(np.round(proba,decimals=3))

[[0.002 0.    0.969 0.001 0.    0.    0.028]
 [0.    0.001 0.01  0.    0.    0.989 0.   ]
 [1.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.913 0.003 0.055 0.    0.028]
 [0.999 0.    0.    0.    0.    0.    0.001]]


In [144]:
proba = lr.predict_proba(train_scaled[:5])
np.round(proba,decimals=3)

array([[0.004, 0.027, 0.705, 0.021, 0.199, 0.012, 0.031],
       [0.002, 0.112, 0.293, 0.003, 0.181, 0.398, 0.01 ],
       [0.061, 0.073, 0.54 , 0.032, 0.211, 0.001, 0.081],
       [0.006, 0.058, 0.632, 0.012, 0.237, 0.02 , 0.034],
       [0.041, 0.099, 0.46 , 0.031, 0.297, 0.005, 0.067]])

In [145]:
decision = lr.decision_function(test_scaled[:5])
print(np.round(decision,decimals=2))

[[  3.19  -2.43   5.53   2.68   0.28 -12.5    3.25]
 [ -4.9    1.45   2.43  -3.68   1.49   5.22  -2.01]
 [  7.04   0.77   1.48   1.39  -0.14 -13.1    2.56]
 [ -0.72  -0.52   3.07  -0.11   1.51  -3.78   0.55]
 [  6.32   1.29   1.58   0.09   0.05 -11.61   2.28]]


In [146]:
from scipy.special import softmax

proba = softmax(decision,axis = 1)
print(np.round(proba,decimals=3))

[[0.076 0.    0.793 0.046 0.004 0.    0.081]
 [0.    0.021 0.055 0.    0.022 0.902 0.001]
 [0.979 0.002 0.004 0.003 0.001 0.    0.011]
 [0.016 0.02  0.722 0.03  0.153 0.001 0.058]
 [0.965 0.006 0.008 0.002 0.002 0.    0.017]]
